export const Questions = [
  {
    prompt: "What is the correct command to create a new React project?",
    optionA: "npx create-react-app myReactApp ",
    optionB: "npx create-react-app",
    optionC: "npm create-react-app myReactApp",
    optionD: "npm create-react-app",
    answer: "optionA",
  },
  {
    prompt: "What does myReactApp refer to in the following command?",
    optionA: "The name you want to use for the new app  ",
    optionB: "A reference to an existing app",
    optionC: "The type of app to create",
    optionD: "The directory to create the new app in",
    answer: "optionA",
  },
  {
    prompt: "What command is used to start the React local development server?",
    optionA: "npm start",
    optionB: "npm run dev",
    optionC: "npm serve",
    optionD: "npm build",
    answer: "optionA",
  },
  {
    prompt: "What is the default local host port that a React development server uses?",
    optionA: "3000",
    optionB: "3500",
    optionC: "8080",
    optionD: "5000",
    answer: "optionA",
  },
  {
    prompt: "To develop and run React code, Node.js is required.",
    optionA: "True",
    optionB: "False",
    optionC: "Can be true or false",
    optionD: "Cannot say",
    answer: "optionA",
  },

  {
    prompt: "What is the children prop?",
    optionA: "A property that lets you pass data to child components  ",
    optionB: "A property that lets you nest components in other components  ",
    optionC: "A property that adds child values to state",
    optionD: "A property that lets you set an object as a property",
    answer: "optionB",
  },
  {
    prompt: "Which keyword creates a constant in JavaScript?",
    optionA: "var",
    optionB: "let",
    optionC: "const",
    optionD: "constant",
    answer: "optionC",
  },

  {
    prompt: "Which of the following option is correct in the case of the Babel?",
    optionA: "Babel is a Compiler.",
    optionB: "Babel is a Transpilar.",
    optionC: "None of the above.",
    optionD: "Both A and B are correct.",
    answer: "optionD",
  },
  {
    prompt: "What does ES6 stand for?",
    optionA: "ECMAScript 6",
    optionB: "ECMA 6",
    optionC: "ECMAJavaScript 6",
    optionD: "EJavaScript 6",
    answer: "optionA",
  },
  {
    prompt: "Which of the following statement is true for uncontrolled components in React.js?",
    optionA: "The source of truth is DOM.",
    optionB: "The source of truth is a component state.",
    optionC: "The source of truth can be anything.",
    optionD: "None of the above.",
    answer: "optionA",
  },

];
